name: kanisaapp
description: "KANISANI"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl:
  flutter_sfsymbols:
  cached_network_image:
  expansion_tile_card:
  youtube_player_flutter:
  shared_preferences:
  google_fonts: ^6.3.3
  lottie:
  # data_connection_checker:
  line_awesome_flutter:
  flutter_screenutil:
  share_plus:
  firebase_database:
  firebase_messaging:
  flutter_local_notifications: ^19.5.0
  image_picker:
  file_picker: ^10.3.7
  provider:
  url_launcher:
  focused_menu:
  scrollable_positioned_list:
  device_preview:
  ffi: ^2.1.4
  fluttertoast:
  local_auth:
  firebase_core:
  # cloud_firestore:
  firebase_storage:
  flutter_staggered_animations: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # To add assets to your application, add an assets section, like this:

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/payicons/
